version: "3.4"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}exapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIROMENT=Development
      - ConnectionString=Server=ExcursionBDCloud.mssql.somee.com;Database=ExcursionBDCloud;User Id=YourSneakyLiar_SQLLogin_1;Password=b51odpedu3;MultipleActiveResultSets=true; TrustServerCertificate=True;
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Password_123"
      - "ACCEPT_EULA=Y"
    container_name: ExcursionApi
    ports:
      - "1555:1433" 

 
